DROP TRIGGER IF EXISTS episode_records_sync_delete;
DROP TRIGGER IF EXISTS episode_records_sync_update;
DROP TRIGGER IF EXISTS episode_records_sync_insert;
DROP TRIGGER IF EXISTS recordings_sync_delete;
DROP TRIGGER IF EXISTS recordings_sync_update;
DROP TRIGGER IF EXISTS recordings_sync_insert;
DROP TABLE IF EXISTS sync_changes;

ALTER TABLE recordings
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE episode_records
    MODIFY COLUMN completed_at DATETIME NULL,
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
