ALTER TABLE users ADD COLUMN nickname VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'User nickname' AFTER username;
ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'User email' AFTER nickname;
ALTER TABLE users ADD COLUMN avatar VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'User avatar URL' AFTER email;